/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification;

import de.testcompany.Event_Notification.utils.HTTPClient;
import de.testcompany.Event_Notification.models.shared.Security;

class SDKConfiguration {
	public HTTPClient defaultClient;
	public HTTPClient securityClient;
	public Security security;
	public String serverUrl;
	public int serverIdx = 0;
	public String language = "java";
	public String openapiDocVersion = "1.2.0";
	public String sdkVersion = "0.4.1";
	public String genVersion = "2.253.0";
	public String userAgent = "speakeasy-sdk/java 0.4.1 2.253.0 1.2.0 de.testcompany.Event_Notification";
	
	
}