/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetCategoriesResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public GetCategoriesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * List of Event Type Categories.
     */
    
    public de.testcompany.Event_Notification.models.shared.EventCategoryDescriptions eventCategoryDescriptions;

    public GetCategoriesResponse withEventCategoryDescriptions(de.testcompany.Event_Notification.models.shared.EventCategoryDescriptions eventCategoryDescriptions) {
        this.eventCategoryDescriptions = eventCategoryDescriptions;
        return this;
    }
    
    /**
     * Unauthorized
     */
    
    public de.testcompany.Event_Notification.models.shared.OAuthProblem oAuthProblem;

    public GetCategoriesResponse withOAuthProblem(de.testcompany.Event_Notification.models.shared.OAuthProblem oAuthProblem) {
        this.oAuthProblem = oAuthProblem;
        return this;
    }
    
    /**
     * Bad Request
     */
    
    public de.testcompany.Event_Notification.models.shared.Rfc7807Problem rfc7807Problem;

    public GetCategoriesResponse withRfc7807Problem(de.testcompany.Event_Notification.models.shared.Rfc7807Problem rfc7807Problem) {
        this.rfc7807Problem = rfc7807Problem;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public GetCategoriesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public GetCategoriesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetCategoriesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
