/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetEventsResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public GetEventsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * List of event notifications.
     */
    
    public de.testcompany.Event_Notification.models.shared.Events events;

    public GetEventsResponse withEvents(de.testcompany.Event_Notification.models.shared.Events events) {
        this.events = events;
        return this;
    }
    
    /**
     * Unauthorized
     */
    
    public de.testcompany.Event_Notification.models.shared.OAuthProblem oAuthProblem;

    public GetEventsResponse withOAuthProblem(de.testcompany.Event_Notification.models.shared.OAuthProblem oAuthProblem) {
        this.oAuthProblem = oAuthProblem;
        return this;
    }
    
    /**
     * Bad Request
     */
    
    public de.testcompany.Event_Notification.models.shared.Rfc7807Problem rfc7807Problem;

    public GetEventsResponse withRfc7807Problem(de.testcompany.Event_Notification.models.shared.Rfc7807Problem rfc7807Problem) {
        this.rfc7807Problem = rfc7807Problem;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public GetEventsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public GetEventsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetEventsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode, @JsonProperty("RawResponse") HttpResponse<byte[]> rawResponse) {
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
  }
}
