/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetNameResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public GetNameResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Specific Event Type Name.
     */
    
    public de.testcompany.Event_Notification.models.shared.EventNameDescription eventNameDescription;

    public GetNameResponse withEventNameDescription(de.testcompany.Event_Notification.models.shared.EventNameDescription eventNameDescription) {
        this.eventNameDescription = eventNameDescription;
        return this;
    }
    
    /**
     * Unauthorized
     */
    
    public de.testcompany.Event_Notification.models.shared.OAuthProblem oAuthProblem;

    public GetNameResponse withOAuthProblem(de.testcompany.Event_Notification.models.shared.OAuthProblem oAuthProblem) {
        this.oAuthProblem = oAuthProblem;
        return this;
    }
    
    /**
     * Bad Request
     */
    
    public de.testcompany.Event_Notification.models.shared.Rfc7807Problem rfc7807Problem;

    public GetNameResponse withRfc7807Problem(de.testcompany.Event_Notification.models.shared.Rfc7807Problem rfc7807Problem) {
        this.rfc7807Problem = rfc7807Problem;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public GetNameResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public GetNameResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetNameResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode, @JsonProperty("RawResponse") HttpResponse<byte[]> rawResponse) {
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
  }
}
