/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import de.testcompany.Event_Notification.utils.SpeakeasyMetadata;


public class GetNameRequest {
    /**
     * The unique name of a specific Event Type Category.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=typeCategory")
    public String typeCategory;

    public GetNameRequest withTypeCategory(String typeCategory) {
        this.typeCategory = typeCategory;
        return this;
    }
    
    /**
     * The unique name of a specific Event Type Name.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=typeName")
    public String typeName;

    public GetNameRequest withTypeName(String typeName) {
        this.typeName = typeName;
        return this;
    }
    
    /**
     * Optional language (EN/DE). The default is EN.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=language")
    public String language;

    public GetNameRequest withLanguage(String language) {
        this.language = language;
        return this;
    }
    
    public GetNameRequest(@JsonProperty("typeCategory") String typeCategory, @JsonProperty("typeName") String typeName) {
        this.typeCategory = typeCategory;
        this.typeName = typeName;
  }
}
