/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Callback - Resource to acknowledge a specific Event.
 */

public class Callback {
    /**
     * The token for the callback request. This token must be returned in the callback response to acknowledge that events were received.
     */
    @JsonProperty("callbackToken")
    public String callbackToken;

    public Callback withCallbackToken(String callbackToken) {
        this.callbackToken = callbackToken;
        return this;
    }
    
    public Callback(@JsonProperty("callbackToken") String callbackToken) {
        this.callbackToken = callbackToken;
  }
}
