/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Cursor - A cursor refers to a random string of characters which marks a specific item in a collection of data.
 * 
 * The cursor will always point to the item, however it will be invalidated if the item is deleted or removed.
 * 
 */

public class Cursor {
    /**
     * This is the cursor that points to the end of the page of data that has been returned.
     * 
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("after")
    public String after;

    public Cursor withAfter(String after) {
        this.after = after;
        return this;
    }
    
    /**
     * This is the cursor that points to the start of the page of data that has been returned.
     * 
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("before")
    public String before;

    public Cursor withBefore(String before) {
        this.before = before;
        return this;
    }
    
    public Cursor(){}
}
