/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * EndPointEndPointType - The specific endPointType, holding information, how you receive your Events.
 */
public enum EndPointEndPointType {
    NONE("None"),
    WEBHOOK("Webhook");

    @JsonValue
    public final String value;

    private EndPointEndPointType(String value) {
        this.value = value;
    }
}
