/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * EventsWithoutPaging - Events
 */

public class EventsWithoutPaging {
    /**
     * Array of event notifications.
     */
    @JsonProperty("data")
    public Event[] data;

    public EventsWithoutPaging withData(Event[] data) {
        this.data = data;
        return this;
    }
    
    public EventsWithoutPaging(@JsonProperty("data") Event[] data) {
        this.data = data;
  }
}
