/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * EventCategoryDescriptions - List of Event type specific category with descriptions
 */

public class EventCategoryDescriptions {
    /**
     * Array containing response data.
     */
    @JsonProperty("data")
    public EventCategoryDescription[] data;

    public EventCategoryDescriptions withData(EventCategoryDescription[] data) {
        this.data = data;
        return this;
    }
    
    public EventCategoryDescriptions(@JsonProperty("data") EventCategoryDescription[] data) {
        this.data = data;
  }
}
