/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * EventTypeSingle - Event type specific category and name.
 */

public class EventTypeSingle {
    /**
     * Event type specific category.
     */
    @JsonProperty("category")
    public String category;

    public EventTypeSingle withCategory(String category) {
        this.category = category;
        return this;
    }
    
    /**
     * General Event type specific name.
     * 
     */
    @JsonProperty("name")
    public String name;

    public EventTypeSingle withName(String name) {
        this.name = name;
        return this;
    }
    
    public EventTypeSingle(@JsonProperty("category") String category, @JsonProperty("name") String name) {
        this.category = category;
        this.name = name;
  }
}
