/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * EventNameDescriptions - List of Event type specific names with descriptions
 */

public class EventNameDescriptions {
    /**
     * Array containing response data.
     */
    @JsonProperty("data")
    public EventNameDescription[] data;

    public EventNameDescriptions withData(EventNameDescription[] data) {
        this.data = data;
        return this;
    }
    
    public EventNameDescriptions(@JsonProperty("data") EventNameDescription[] data) {
        this.data = data;
  }
}
