/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * EventNameDescription - Event type specific category and names with descriptions
 */

public class EventNameDescription {
    /**
     * Description of an Event type specific name.
     */
    @JsonProperty("description")
    public String description;

    public EventNameDescription withDescription(String description) {
        this.description = description;
        return this;
    }
    
    /**
     * Event type specific name.
     */
    @JsonProperty("name")
    public String name;

    public EventNameDescription withName(String name) {
        this.name = name;
        return this;
    }
    
    public EventNameDescription(@JsonProperty("description") String description, @JsonProperty("name") String name) {
        this.description = description;
        this.name = name;
  }
}
