/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * OAuthProblem - Error during authentication
 */

public class OAuthProblem {
    /**
     * Error message
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("error")
    public String error;

    public OAuthProblem withError(String error) {
        this.error = error;
        return this;
    }
    
    /**
     * Further description of the error pattern.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("error_description")
    public String errorDescription;

    public OAuthProblem withErrorDescription(String errorDescription) {
        this.errorDescription = errorDescription;
        return this;
    }
    
    public OAuthProblem(){}
}
