/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PatchOperationEvent - All patchable data of an Event.
 */

public class PatchOperationEvent {
    /**
     * The unique id of the Event which should be patched.
     */
    @JsonProperty("eventId")
    public String eventId;

    public PatchOperationEvent withEventId(String eventId) {
        this.eventId = eventId;
        return this;
    }
    
    /**
     * An operation is applied to the data structures represented by a JSON document.
     */
    @JsonProperty("op")
    public PatchOperation op;

    public PatchOperationEvent withOp(PatchOperation op) {
        this.op = op;
        return this;
    }
    
    /**
     * Patchable paths of an Event.
     */
    @JsonProperty("path")
    public Path path;

    public PatchOperationEvent withPath(Path path) {
        this.path = path;
        return this;
    }
    
    /**
     * New value to be set by the operation.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    public String value;

    public PatchOperationEvent withValue(String value) {
        this.value = value;
        return this;
    }
    
    public PatchOperationEvent(@JsonProperty("eventId") String eventId, @JsonProperty("op") PatchOperation op, @JsonProperty("path") Path path) {
        this.eventId = eventId;
        this.op = op;
        this.path = path;
  }
}
