/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PatchOperationSubscription - All patchable data of a subscription.
 */

public class PatchOperationSubscription {
    /**
     * An operation is applied to the data structures represented by a JSON document.
     */
    @JsonProperty("op")
    public PatchOperation op;

    public PatchOperationSubscription withOp(PatchOperation op) {
        this.op = op;
        return this;
    }
    
    /**
     * Patchable paths of a subscription.
     */
    @JsonProperty("path")
    public PatchOperationSubscriptionPath path;

    public PatchOperationSubscription withPath(PatchOperationSubscriptionPath path) {
        this.path = path;
        return this;
    }
    
    /**
     * New value to be set by the operation.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    public String value;

    public PatchOperationSubscription withValue(String value) {
        this.value = value;
        return this;
    }
    
    public PatchOperationSubscription(@JsonProperty("op") PatchOperation op, @JsonProperty("path") PatchOperationSubscriptionPath path) {
        this.op = op;
        this.path = path;
  }
}
