/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PatchOperation - An operation is applied to the data structures represented by a JSON document.
 */
public enum PatchOperation {
    REPLACE("replace");

    @JsonValue
    public final String value;

    private PatchOperation(String value) {
        this.value = value;
    }
}
