/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Path - Patchable paths of an Event.
 */
public enum Path {
    ROOT_EVENT_STATUS("/eventStatus");

    @JsonValue
    public final String value;

    private Path(String value) {
        this.value = value;
    }
}
