/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ServiceInfo - DE: Informationen zur API &lt;br/&gt; EN: provides information about the API
 * 
 */

public class ServiceInfo {
    /**
     * DE: Die aktuell verwendete Version der API Spezifikation &lt;br/&gt; EN: The currently used version of the API specification
     * 
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("apiSpecificationVersion")
    public String apiSpecificationVersion;

    public ServiceInfo withApiSpecificationVersion(String apiSpecificationVersion) {
        this.apiSpecificationVersion = apiSpecificationVersion;
        return this;
    }
    
    public ServiceInfo(){}
}
