/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Subscriptions - List of several Subscription ressources.
 */

public class Subscriptions {
    /**
     * Array containing response data.
     */
    @JsonProperty("data")
    public Subscription[] data;

    public Subscriptions withData(Subscription[] data) {
        this.data = data;
        return this;
    }
    
    /**
     * Cursor-based pagination to improve performance and minimize networks traffic, Pagination is enforced for operations
     * that potentially could return a large collection of items.
     * 
     */
    @JsonProperty("paging")
    public PageableResultInfo paging;

    public Subscriptions withPaging(PageableResultInfo paging) {
        this.paging = paging;
        return this;
    }
    
    public Subscriptions(@JsonProperty("data") Subscription[] data, @JsonProperty("paging") PageableResultInfo paging) {
        this.data = data;
        this.paging = paging;
  }
}
