/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SubscriptionInput - Ressource that contains all data to manage an Event Subscription.
 */

public class SubscriptionInput {
    /**
     * The id of the Company, for which the Subscription is applicable.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("companyId")
    public Long companyId;

    public SubscriptionInput withCompanyId(Long companyId) {
        this.companyId = companyId;
        return this;
    }
    
    /**
     * Endpoint to receive event notifications.
     */
    @JsonProperty("endPoint")
    public EndPoint endPoint;

    public SubscriptionInput withEndPoint(EndPoint endPoint) {
        this.endPoint = endPoint;
        return this;
    }
    
    /**
     * Array of event notification types to subscribe to. 
     * An empty array means subscribe to all types.
     * 
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("eventTypes")
    public EventType[] eventTypes;

    public SubscriptionInput withEventTypes(EventType[] eventTypes) {
        this.eventTypes = eventTypes;
        return this;
    }
    
    /**
     * The id of the Loan partner, for which the Subscription is applicable.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("loanPartnerId")
    public String loanPartnerId;

    public SubscriptionInput withLoanPartnerId(String loanPartnerId) {
        this.loanPartnerId = loanPartnerId;
        return this;
    }
    
    /**
     * Human readable name of your given Subscription.
     */
    @JsonProperty("subscriptionName")
    public String subscriptionName;

    public SubscriptionInput withSubscriptionName(String subscriptionName) {
        this.subscriptionName = subscriptionName;
        return this;
    }
    
    public SubscriptionInput(@JsonProperty("endPoint") EndPoint endPoint, @JsonProperty("subscriptionName") String subscriptionName) {
        this.endPoint = endPoint;
        this.subscriptionName = subscriptionName;
  }
}
