/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package de.testcompany.Event_Notification.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Subscription - Ressource that contains all data to manage an Event Subscription.
 */

public class Subscription {
    /**
     * The id of the Company, for which the Subscription is applicable.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("companyId")
    public Long companyId;

    public Subscription withCompanyId(Long companyId) {
        this.companyId = companyId;
        return this;
    }
    
    /**
     * Endpoint to receive event notifications.
     */
    @JsonProperty("endPoint")
    public EndPoint endPoint;

    public Subscription withEndPoint(EndPoint endPoint) {
        this.endPoint = endPoint;
        return this;
    }
    
    /**
     * Array of event notification types to subscribe to. 
     * An empty array means subscribe to all types.
     * 
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("eventTypes")
    public EventType[] eventTypes;

    public Subscription withEventTypes(EventType[] eventTypes) {
        this.eventTypes = eventTypes;
        return this;
    }
    
    /**
     * The id of the Loan partner, for which the Subscription is applicable.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("loanPartnerId")
    public String loanPartnerId;

    public Subscription withLoanPartnerId(String loanPartnerId) {
        this.loanPartnerId = loanPartnerId;
        return this;
    }
    
    /**
     * Primary Key of a Subscription.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("subscriptionId")
    public String subscriptionId;

    public Subscription withSubscriptionId(String subscriptionId) {
        this.subscriptionId = subscriptionId;
        return this;
    }
    
    /**
     * Human readable name of your given Subscription.
     */
    @JsonProperty("subscriptionName")
    public String subscriptionName;

    public Subscription withSubscriptionName(String subscriptionName) {
        this.subscriptionName = subscriptionName;
        return this;
    }
    
    public Subscription(@JsonProperty("endPoint") EndPoint endPoint, @JsonProperty("subscriptionName") String subscriptionName) {
        this.endPoint = endPoint;
        this.subscriptionName = subscriptionName;
  }
}
